"""
    Merge Accounting API

    The unified API for building rich integrations with multiple Accounting & Finance platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeAccountingClient
from MergeAccountingClient.model.remote_data import RemoteData
from MergeAccountingClient.model.transaction_line_item import TransactionLineItem
globals()['RemoteData'] = RemoteData
globals()['TransactionLineItem'] = TransactionLineItem
from MergeAccountingClient.model.transaction import Transaction
from MergeAccountingClient.api_client import ApiClient


class TestTransaction(unittest.TestCase):
    """Transaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransaction(self):
        """Test Transaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Transaction()  # noqa: E501

        """
        No test json responses were defined for Transaction
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (Transaction,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
